package ru.kravchenkoanatoly.githubusers.models

import java.io.Serializable

data class GithubUserInfoDomain(
    val avatarUrl: String?,
    val bio: Any?,
    val blog: String?,
    val company: Any?,
    val createdAt: String?,
    val documentationUrl: String?,
    val email: Any?,
    val eventsUrl: String?,
    val followers: Int?,
    val followersUrl: String?,
    val following: Int?,
    val followingUrl: String?,
    val gistsUrl: String,
    val gravatarId: String,
    val hireable: Any?,
    val htmlUrl: String?,
    val id: Int?,
    val location: Any?,
    val login: String?,
    val message: String?,
    val name: Any?,
    val nodeId: String?,
    val organizationsUrl: String?,
    val publicGists: Int?,
    val publicRepos: Int?,
    val receivedEventsUrl: String?,
    val reposUrl: String?,
    val siteAdmin: Boolean?,
    val starredUrl: String?,
    val subscriptionsUrl: String?,
    val twitterUsername: Any?,
    val type: String?,
    val updatedAt: String?,
    val url: String?
): Serializable
